apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: biely-ambulance-ufe-content
spec:
  microFrontend: biely-ambulance-ufe
  element: biely-ambulance-wl-list
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?biely-ambulance-wl(/.*)?$"